file(REMOVE_RECURSE "${OUTPUT_ROOT}")
foreach(layout flat chunked)
    execute_process(COMMAND "${GENERATOR}" "${OUTPUT_ROOT}" "${layout}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "SDK fixture generation failed for ${layout}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SMOKE_SOURCE}" -B "${OUTPUT_ROOT}/build-${layout}" -DSDK_A_DIR=${OUTPUT_ROOT}/${layout}/SDK_A -DSDK_SMOKE_RUN=ON RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "SDK smoke configuration failed for ${layout}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${OUTPUT_ROOT}/build-${layout}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Generated SDK compilation failed for ${layout}")
    endif()
    execute_process(COMMAND "${OUTPUT_ROOT}/build-${layout}/sdk_smoke_exec" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Generated SDK owned array execution failed for ${layout}")
    endif()
endforeach()
