#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CoreUObject

#include "Basic.h"

#include "CoreUObject_classes.h"
#include "CoreUObject_parameters.h"
#include "UnrealContainers.h"
#include <atomic>
#include <cstdint>


namespace SDK
{

// Predefined Function
// Finds a UObject in the global object array by name, optionally with ECastFlags to reduce heavy string comparison

class UObject* UObject::FindObjectFastImpl(const std::string& Name, EClassCastFlags RequiredType)
{
	for (int i = 0; i < GObjects->Num(); ++i)
	{
		UObject* Object = GObjects->GetByIndex(i);
	
		if (!Object)
			continue;

		// LOGI("FindObjectFastImpl: %s, Name: %s", Object->GetName().c_str(), Name.c_str());

		if (Object->HasTypeFlag(RequiredType) && Object->GetName() == Name)
			return Object;
	}

	LOGI("FindObjectFastImpl: %s not found", Name.c_str());

	return nullptr;
}


// Predefined Function
// Finds a UObject in the global object array by full-name, optionally with ECastFlags to reduce heavy string comparison

class UObject* UObject::FindObjectImpl(const std::string& FullName, EClassCastFlags RequiredType)
{
	// static std::atomic_bool g_thread_stared = false;
	// if (!g_thread_stared) {
	// 	g_thread_stared = true;
	// 	std::thread([=]() {
	// 		LOGI("[GetAllObjects] Enter");
	// 		for (int i = 0; i < GObjects->Num(); ++i) {
	// 			UObject* Object = GObjects->GetByIndex(i);
	// 			if (!Object)
	// 				continue;
	// 			std::string ObjectName = Object->GetFullName();
	// 			LOGI("[GetAllObjects] %d, %s", Object->Name.DisplayIndex, Object->GetFullName().c_str());
	// 			std::this_thread::sleep_for(std::chrono::milliseconds(1));
	// 		}
	// 		LOGI("[GetAllObjects] Done");
	// 	}).detach();
	// }

	for (int i = 0; i < GObjects->Num(); ++i)
	{
		UObject* Object = GObjects->GetByIndex(i);

		if (!Object || ((uint64_t)Object & 0x7) != 0)
			continue;

		// LOGI("[%d, %p] FindObjectImpl: %s", i, Object, Object->GetFullName().c_str());

		if (Object->HasTypeFlag(RequiredType) && Object->GetFullName() == FullName)
			return Object;
	}

	LOGI("FindObjectImpl: %s not found", FullName.c_str());

	return nullptr;
}


// Predefined Function
// Returns the name of this object in the format 'Class Package.Outer.Object'

std::string UObject::GetFullName() const
{
	if (this && Class)
	{
		std::string Temp;

		for (UObject* NextOuter = Outer; NextOuter; NextOuter = NextOuter->Outer)
		{
			Temp = NextOuter->GetName() + "." + Temp;
		}

		std::string Name = Class->GetName();
		Name += " ";
		Name += Temp;
		Name += GetName();

		return Name;
	}

	return "None";
}


// Predefined Function
// Returns the name of this object

std::string UObject::GetName() const
{
	return this ? Name.ToString() : "None";
}


// Predefined Function
// Checks Class->FunctionFlags for TypeFlags

bool UObject::HasTypeFlag(enum EClassCastFlags TypeFlags) const
{
	using T = std::underlying_type_t<EClassCastFlags>;
	// LOGI("HasTypeFlag: %d, %d, %d", static_cast<T>(Class->CastFlags), static_cast<T>(TypeFlags), static_cast<T>(Class->CastFlags) & static_cast<T>(TypeFlags));
	// return true;
	return TypeFlags == EClassCastFlags::None || static_cast<T>(Class->CastFlags) & static_cast<T>(TypeFlags);
}


// Predefined Function
// Checks a UObjects' type by TypeFlags

bool UObject::IsA(enum EClassCastFlags TypeFlags) const
{
	using T = std::underlying_type_t<EClassCastFlags>;
	// LOGI("HasTypeFlag: %d, %d, %d", static_cast<T>(Class->CastFlags), static_cast<T>(TypeFlags), static_cast<T>(Class->CastFlags) & static_cast<T>(TypeFlags));
	// return true;
	return TypeFlags == EClassCastFlags::None || static_cast<T>(Class->CastFlags) & static_cast<T>(TypeFlags);
}


// Predefined Function
// Checks a UObjects' type by Class

bool UObject::IsA(class UClass* TypeClass) const
{
	return Class->IsSubclassOf(TypeClass);
}


// Predefined Function
// Checks whether this object is a classes' default-object

bool UObject::IsDefaultObject() const
{
	return Flags & static_cast<int32_t>(EObjectFlags::ClassDefaultObject);
}


// Function CoreUObject.Object.ExecuteUbergraph
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UObject::ExecuteUbergraph(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Object", "ExecuteUbergraph");

	Params::Object_ExecuteUbergraph Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


void UObject::TraverseSupers(const std::function<bool(const UObject*)>& Callback) const
{
	for (const UStruct* Clss = this->HasTypeFlag(EClassCastFlags::Class)
			? static_cast<const UClass*>(this) : this->Class; Clss; Clss = Clss->Super)
	{
		if (!Callback(Clss))
			break;
	}
}


// Predefined Function
// Checks if this class has a certain base

bool UStruct::IsSubclassOf(const UStruct* Base) const
{
	if (!Base)
		return false;

	for (const UStruct* Struct = this; Struct; Struct = Struct->Super)
	{
		if (Struct == Base)
			return true;
	}

	return false;
}


// Predefined Function
// Gets a UFunction from this UClasses' 'Children' list

class UFunction* UClass::GetFunction(const std::string& ClassName, const std::string& FuncName) const
{
	for (const UStruct* Clss = this; Clss; Clss = Clss->Super)
	{
		// LOGI("UClass::GetFunction ClassName: %s, %s", Clss->GetName().c_str(), ClassName.c_str());
		if (Clss->GetName() != ClassName)
			continue;

		// LOGI("UClass::GetFunction Children: %p, %s", Clss->Children, Clss->Children->GetName().c_str());

		for (UField* Field = Clss->Children; Field; Field = Field->Next)
		{
			// LOGI("UClass::GetFunction FuncName: %p, %s, %s", Field, Field->GetName().c_str(), FuncName.c_str());
			if (Field->HasTypeFlag(EClassCastFlags::Function) && Field->GetName() == FuncName)
				return static_cast<class UFunction*>(Field);
		}
	}

    LOGI("UClass::GetFunction: %s.%s not found", ClassName.c_str(), FuncName.c_str());

	return nullptr;
}

}

