#!/usr/bin/env python3
"""Extract the pinned, private AndUEDumper text emitter with checked transforms."""

import argparse
import hashlib
import json
from pathlib import Path
import subprocess

REVISION = "17aa3c5ff971af4502f33b51cebf049f09a78506"
INPUTS = {
    "LICENSE": "6ad5720f2b9b0f5670438cf7feb7552c7103668fe21fa67a0409af2a2c9c7b95",
    "deps/fmt/LICENSE": "07580f2a3b35709ce703d523f447b242f6dfec7582a8c0df102c7fa2849375f8",
    "AndUEDumper/src/UPackageGenerator.cpp": "b6cb231c595766de296b3b089f7e4c4d422948a37153526ceb78bf14cc36ef83",
    "AndUEDumper/src/UPackageGenerator.hpp": "95f5f866b2502b79eacbe368c7cd0f249d91649ddecd8d53b3e9596b7e08f180",
    "deps/fmt/format.h": "f6515852b0b0375fb05d27d27cd386da4c6aff40a4fb9232413f604c8c49b6d8",
    "deps/fmt/base.h": "b0d52ef9d0f7203100eeee451056938e11536894feff6f99a6566497d6f40d4b",
    "deps/fmt/format-inl.h": "02f79502fc57326bbafec8f07c2b664ac0bcb83cb444ee464359dba83c10c36f",
}


def digest(data):
    return hashlib.sha256(data).hexdigest()


def replace_exact(text, old, new, count=1):
    actual = text.count(old)
    if actual != count:
        raise ValueError(f"transform expected {count} occurrences, found {actual}: {old!r}")
    return text.replace(old, new)


def extract(root, output):
    revision = subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "HEAD"], text=True).strip()
    if revision != REVISION:
        raise ValueError(f"AndUEDumper revision mismatch: {revision}")
    for name, expected in INPUTS.items():
        actual = digest((root / name).read_bytes())
        if actual != expected:
            raise ValueError(f"AndUEDumper source digest mismatch: {name}: {actual}")
    header = (root / "AndUEDumper/src/UPackageGenerator.hpp").read_text()
    source = (root / "AndUEDumper/src/UPackageGenerator.cpp").read_text()
    declarations = header[header.index("    struct Member\n"):header.index("\nprivate:\n")]
    body = source[source.index("void UE_UPackage::AppendStructsToBuffer("):source.index("void UE_UPackage::Process(")]
    body = replace_exact(body, "UE_UPackage::", "ExtractedPackage::", 2)
    body = replace_exact(body,
        "void *funcOffset = f.Func ? (void *)(f.Func - UEWrappers::GetUEVars()->GetBaseAddress()) : nullptr;",
        "void *funcOffset = nullptr;")
    body = replace_exact(body, "std::string seg;", "BufferFmt seg(pBufFmt->limits());", 2)
    body = replace_exact(body, 'seg += "\\n";', 'seg.append("\\n");')
    body = replace_exact(body, 'seg += "\\n\\n";', 'seg.append("\\n\\n");')
    body = replace_exact(body, "seg += fmt::format(", "seg.append(", 3)
    body = replace_exact(body, "segs.push_back(std::move(seg));", "segs.push_back(seg.read());", 2)
    body = replace_exact(body, "qualify(e.CppNameOnly, m.first), m.second",
                         "qualify(e.CppNameOnly, m.first), formatEnumValue(e.UnderlyingType, m.second)", 2)
    # This comment documents an upstream maintenance process, not an emitter invariant.
    body = replace_exact(body, "// rewrite them. Add new entries as they show up.", "// rewrite them.")
    if any(token in body for token in ("UEWrappers", "GetUEVars", "UEMemory", "fmt::format(")):
        raise ValueError("unexpected live dependency or unbounded formatting in extracted emitter")
    notice = (
        "// Derived from AndUEDumper UPackageGenerator, revision " + REVISION + ".\n"
        "// Copyright (c) 2022 CyberCat. MIT license: licenses/AndUEProber/AndUEDumper/LICENSE.\n"
        "// Generated by tools/extract_dumper_emitter.py; do not edit.\n")
    generated = {
        "UpstreamEmitter.hpp": notice + "#pragma once\n#include <cstdint>\n#include <set>\n#include <string>\n#include <utility>\n#include <vector>\nnamespace andueprober::dumper_emitter {\nclass BufferFmt;\nclass ExtractedPackage {\npublic:\n" + declarations + "\n    static void AppendStructsToBuffer(std::vector<Struct>&, BufferFmt*);\n    static void AppendEnumsToBuffer(std::vector<Enum>&, BufferFmt*);\n};\n}\n",
        "UpstreamEmitter.cpp": notice + '#include "UpstreamEmitter.hpp"\n#include "BoundedBuffer.hpp"\n#include <unordered_set>\nnamespace andueprober::dumper_emitter {\n' + body + "\n}\n",
    }
    output.mkdir(parents=True, exist_ok=True)
    for name, content in generated.items():
        path = output / name
        data = content.encode()
        if not path.exists() or path.read_bytes() != data:
            path.write_bytes(data)
    provenance = {
        "schema_version": 1,
        "upstream_revision": revision,
        "upstream_url": "https://github.com/DumpA1n/AndUEDumper",
        "input_sha256": INPUTS,
        "generator_sha256": digest(Path(__file__).read_bytes()),
        "generated_sha256": {name: digest(content.encode()) for name, content in generated.items()},
        "transformations": [
            "Extract only plain nested data declarations and the two Append methods with the enum macro helper.",
            "Rename the private class and namespace to avoid the live UE_UPackage definition.",
            "Replace the manager-relative function address expression with nullptr; the entry point rejects every nonzero Func.",
            "Replace member/function temporary string formatting with the bounded BufferFmt sink.",
            "Format enum bits through a closed fixed-width integer formatter, preserving signed values and unsigned 64-bit literals.",
            "Remove one upstream maintenance-process comment sentence.",
        ],
    }
    (output / "provenance.json").write_text(json.dumps(provenance, indent=2) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    extract(args.source.resolve(), args.output.resolve())
